# 网站标题设置
subtitle: 鼠鼠の小窝

author:
  website: https://example.com/
  name: 鼠鼠
  avatar: avatar.jpg
  description: A Small Mouse.
  email: xxx@example.com

widget:
  recent:
    enabled: true
  tags:
    enabled: true

theme:
  enabled: true

search:
  enabled: true
