# 网站标题设置
subtitle:

author:
  website:
  name:
  avatar:
  description:
  email:

widget:
  recent:
    enabled: true
  tags:
    enabled: true
  categories:
    enabled: true
    depth: 2 # 推荐为 2 更大的话估计会爆出部件

search:
  enabled: true

toc:
  enabled: true
  numbers: false
  # 最大支持6层
  depth: 6

commits:
  repo:
    name:
    id:
  category:
    name:
    id:
