# 网站标题设置
subtitle: 鼠鼠の小窝

author:
  website: https://example.com/
  name: 鼠鼠
  avatar: avatar.jpg
  description: A Small Mouse.
  email: xxx@example.com

widget:
  recent:
    enabled: true
  tags:
    enabled: true

# 工具栏的设置
toolbars:
  # 主题色切换器
  theme_switcher:
    enabled: true
