name: Publish Release CI

on:
  push:
    branches:
      - "master"
    paths:
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: hexo-theme-hydrogen
          generateReleaseNotes: true
          tag:  ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
